USE tg1;

EXEC SP_CONFIGURE 'SHOW ADVANCE', 1
GO
RECONFIGURE WITH OVERRIDE
GO
EXEC SP_CONFIGURE 'AGENT XPs', 1
GO
RECONFIGURE WITH OVERRIDE
GO

BACKUP DATABASE tg1 TO DISK = 'C:\tg1-bd\tg1.bak' 
	WITH NOFORMAT, NOINIT, NAME = N'TG1-Full-Backup-Tierri-Ferreira-22897', SKIP, NOREWIND, NOUNLOAD, STATS = 10
GO

